package com.offgrid.app.data.model

import java.util.UUID

/** What an OFFGRID node can do on the mesh. Used to drive Nearby Help filtering later. */
enum class DeviceCapability { MESSAGING, RELAY, EMERGENCY_RESPONDER }

enum class NodeStatus { AVAILABLE, CONNECTING, CONNECTED, OFFLINE }

/**
 * A discovered OFFGRID device/peer.
 *
 * [isSimulated] marks demo-only nodes generated by MockCommunicationTransport so the Nearby
 * list isn't empty on a single emulator. The one real link between two running app instances
 * has isSimulated = false — that is the node the two-device demo actually talks to.
 */
data class Node(
    val id: String,
    val name: String,
    val status: NodeStatus = NodeStatus.OFFLINE,
    val lastSeen: Long = System.currentTimeMillis(),
    val signalStrength: Int? = null,
    val hops: Int = 1,
    val isSimulated: Boolean = false,
    val capabilities: Set<DeviceCapability> = setOf(DeviceCapability.MESSAGING),
    /** Stable OFFGRID identity carried in the advertising name; [id] remains the Nearby endpoint id. */
    val logicalId: String = id,
)

enum class MessageStatus { SENDING, DELIVERED, FAILED, RECEIVED }

enum class MessageType { TEXT, EMERGENCY, SYSTEM }

data class Message(
    val id: String = UUID.randomUUID().toString(),
    val conversationId: String,
    val senderId: String,
    val receiverId: String,
    val content: String,
    val timestamp: Long = System.currentTimeMillis(),
    val status: MessageStatus = MessageStatus.SENDING,
    val type: MessageType = MessageType.TEXT,
    /** Stable destination identity used by the mesh router; endpoint ids are local to a link. */
    val recipientNodeId: String? = null,
    /** Number of mesh hops traversed so far. */
    val hopCount: Int = 0,
    /** True when this message arrived through an encrypted mesh hop. */
    val hopEncrypted: Boolean = false,
)

data class Conversation(
    val id: String,
    val peer: Node,
    val messages: List<Message> = emptyList(),
) {
    val lastMessage: Message? get() = messages.lastOrNull()
}

enum class SOSStatus { BROADCASTING, ACTIVE, CANCELLED }

data class SOSAlert(
    val id: String = UUID.randomUUID().toString(),
    val senderId: String,
    val timestamp: Long = System.currentTimeMillis(),
    val status: SOSStatus = SOSStatus.BROADCASTING,
    val message: String = "I'm in an emergency and need help.",
    val location: String? = null,
    val nodesReached: Int = 0,
    val helpersFound: Int = 0,
)

enum class LinkState { OFFLINE, LISTENING, CONNECTING, CONNECTED }

data class NetworkStatus(
    val linkState: LinkState = LinkState.OFFLINE,
    val nearbyCount: Int = 0,
    val transportName: String = "Mock Local Transport",
)
